version: '3'
services:
  tortoisebot-ros1-real:
    build:
      context: ./
      dockerfile: Dockerfile_real
    image: tortoisebot-ros1-real
    container_name: tortoisebot-ros1-real_1
    network_mode: host
    environment:
      - "DISPLAY=${DISPLAY}"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  tortoisebot-ros1-slam:
    build:
      context: ./
      dockerfile: Dockerfile_slam
    image: tortoisebot-ros1-slam
    container_name: tortoisebot-ros1-slam_1
    network_mode: host
    depends_on:
      - tortoisebot-ros1-real
    environment:
      - "DISPLAY=${DISPLAY}"
      - "ROS_MASTER_URI=http://master:11311"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    command: bash -c "source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash && sleep 10 && roslaunch tortoisebot_slam mapping.launch"  # Adjust the sleep time as needed
