FROM ubuntu:20.04

# Install SSH server and SSHpass
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server sshpass && \
    apt-get clean

# Create the 'tortoisebot' user and set its password
RUN useradd -m tortoisebot && \
    echo 'tortoisebot:raspberry' | chpasswd

# Generate host keys
RUN ssh-keygen -A

# Expose SSH port
EXPOSE 22

# Start SSH server and execute commands over SSH
CMD service ssh start && \
    echo "SSH server started. Waiting for SSH to be available..." && \
    echo "SSH server is ready. Executing commands..." && \
    sshpass -p "raspberry" ssh -o StrictHostKeyChecking=no tortoisebot@master "bash -ic 'export ROS_MASTER_URI=http://master:45225/ && noetic && roslaunch tortoisebot_firmware bringup.launch'"
